### ISSUE TITLE
Demo code for single image inference?

### ISSUE THREAD

**Issue by bakachan19** [ofa-x/OFA-X#1]
Hi.
Thanks for this really interesting work.
I was wondering if you could share a demo code for using the model for single-image inference? I am interesting in using the model for reasearch purposes.

Thanks!

**Comment by jakobamb** [comment]
Hi,

you can take a look at this colab notebook from the OFA authors:

https://colab.research.google.com/drive/1lsMsF-Vum3MVyXwSVF5E-Y23rHFvj_3y?usp=sharing#scrollTo=04a82115

You should be able to adapt this to OFA-X by loading the corresponding model checkpoints linked in the Readme.

Hope this helps!

Jakob

**Comment by bakachan19** [comment]
Hi @jakobamb,
The material you provided looks like a good starting point.
I will have a look and see if I can make it work. I will let you know how it goes.

Thank you for your help.
Have a great day!
